### ISSUE TITLE
Support Reload Your Balance page

### ISSUE THREAD

**Issue by compeek** [pip8786/CCNA#10]
Excellent extension! I've been needing this for a long time and happened to check if somebody wrote a Chrome extension for it, and I was delighted to see you did! Thank you so much.

Anyway my suggestion is to make the nicknames work on the "Reload Your Balance" page as well as the "Select a payment method" page you get to when editing the payment method for reloading the gift card balance.

These are the pages:
https://www.amazon.com/asv/reload/order
https://www.amazon.com/asv/reload/change-payment

I suppose it would be good to include the "Auto-Reload Setting" page as well, although I don't personally need it:
https://www.amazon.com/asv/autoreload/

**Comment by pip8786** [comment]
Thanks for the feedback. I'll try to add those soon.

**Comment by pip8786** [comment]
I've added this and published the changes in 1.0.4. Sorry for the long wait, kind of lost track of this issue (and the extension doesn't get much attention from me anymore).

**Comment by compeek** [comment]
Thank you so much! This is really helpful to me.
