### ISSUE TITLE
Duplicate Cards Shown on Amazon Page

### ISSUE THREAD

**Issue by fcastilloec** [pip8786/CCNA#18]
This extension is stuck on `v1.0.8` for Firefox while Chrome is already on `v1.0.10`.
Can you update the Firefox one to be on par with Chrome, and in the future, make sure that both sides are on the same version number?

Thanks!

**Comment by pip8786** [comment]
Are you having an issue on Firefox that I can help with?

**Comment by fcastilloec** [comment]
The only issue I'm seeing is duplicate cards on the extension. Some of my cards are shown twice but the nicknames are not affected

**Comment by pip8786** [comment]
According to #19 it may be because of the default card. Need to make sure we don't show it twice, though we have to be careful not to limit the extension when it comes to having multiple cards with the same number which is possible, especially with Amex.

**Comment by pip8786** [comment]
Fixed this in 1.0.12. Should be out soon.
