### ISSUE TITLE
"This is not an Amazon wallet or payment tab" during checkout.

### ISSUE THREAD

**Issue by Commodork** [pip8786/CCNA#23]
Love this plug-in, been using it for years. Recently it has stopped working during check out, which is the only time I would need to use it. When I dive down into Amazon's list of payments, the nicknames show up there. When I am on the checkout page, they do not show up and I get "This is not an Amazon wallet or payment tab." I have uninstalled and reinstalled the plug-in and reset permissions... not sure what else to do to get it working again? I'm running Chrome on Windows 11, both with current patch levels.

**Comment by pip8786** [comment]
Hey @Commodork . Thanks for the report. It looks like Amazon changed the page so I will need to update the extension. Sorry I've been busy but will get to it this week.

**Comment by pip8786** [comment]
@Commodork looks like they changed the URL and the content of the page itself. I've just submitted 1.0.14 to address those issues. I'll let you know when that version comes through so you can hopefully test the resolution. Thanks for the report!

**Comment by pip8786** [comment]
I've just checked the published extension and it's working for me now. Let me know if it works for you.

**Comment by Commodork** [comment]
I uninstalled and reinstalled to get the latest version and can confirm it's working again. Thanks again for the quick response and update. This plugin is so handy!

**Comment by MM-John** [comment]
1.5 years later, My amazon checkout page is:

https://www.amazon.com/checkout/p/p-AAA-BBBBBBB-CCCCCCC/pay?pipelineType=Chewbacca&referrer=pay

And the nicknames are not appearing. I suppose we will ever be playing catch up.

May I suggest a "force" or something such that the extension tries to find the cards on whatever page is current, even if it is not detected as a "card" page?

**Comment by pip8786** [comment]
@MM-John 

Interesting, my checkout URL is very similar and it still seems to work. I wonder what's going wrong with yours? Could you send screenshots of the checkout page and the extension to my email so I can take a look? You can find the email address here under details: https://chromewebstore.google.com/detail/credit-card-nicknames-for/iodihdkgnjbpkdimohmpgbcfoioebbnf

As for the force option, the problem with that is I'd have to enable the extension on more pages which might have users asking why it needs those permissions. I guess we could keep it to amazon only URLs which would probably help with that. But in the end, each page has very different structure and I specifically search for a pattern on each one to match the credit card information with the nicknames. I'm not sure a force option is feasible.
