### ISSUE TITLE
Add Amazon Smile

### ISSUE THREAD

**Issue by pip8786** [pip8786/CCNA#5]
Feature request in extension comments/reviews found here: https://chrome.google.com/webstore/detail/credit-card-nicknames-for/iodihdkgnjbpkdimohmpgbcfoioebbnf/support

**Comment by LandonSchropp** [comment]
I'm happy to submit a PR for this if that would help get the ball rolling. Would you be up for that?

**Comment by pip8786** [comment]
Yep, go for it. I will support it and push it out to the store when its ready. Thanks!
